services:
  unifi-video-archiver:
    image: unifi-video-archiver:latest
    build:
      context: .
    container_name: unifi-video-archiver
    restart: unless-stopped
    init: true
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./clips:/app/clips
